spring:
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: ********
    #授权码
    password: *********
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://192.168.142.133:3306/crazy_rain_user_center
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  session:
    timeout: 86400
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    port: 6379
    password: 123456
    host: 192.168.142.133
    database: 0
server:
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.crazy.rain.usercenter.model.domain
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: 用户中心接口文档
    description: "用户中心接口文档"
    email: xxxx@qq.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v1
    group:
      test1:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.crazy.rain.usercenter.controller
